const data = [
  {
    id: 'aa11',
    name: 'apple',
    category: 'fruits',
    img: 'img/apple.png',
    price: 40,
    quantity: 2,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'bb22',
    name: 'banana',
    category: 'fruits',
    img: 'img/banana.png',
    price: 50,
    quantity: 3,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'cc33',
    name: 'beer',
    category: 'drinks',
    img: 'img/beer.png',
    price: 60,
    quantity: 5,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'dd44',
    name: 'cucumber',
    category: 'vegetables',
    img: 'img/cucumber.png',
    price: 40,
    quantity: 4,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'ee55',
    name: 'garlic',
    category: 'vegetables',
    img: 'img/garlic.png',
    price: 120,
    quantity: 5,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'ff66',
    name: 'pineapple',
    category: 'fruits',
    img: 'img/pineapple.png',
    price: 80,
    quantity: 6,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'gg77',
    name: 'pumpkin',
    category: 'vegetables',
    img: 'img/pumpkin.png',
    price: 60,
    quantity: 1,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'hh88',
    name: 'strawberry',
    category: 'fruits',
    img: 'img/strawberry.png',
    price: 100,
    quantity: 7,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'ii99',
    name: 'tea',
    category: 'drinks',
    img: 'img/tea.png',
    price: 40,
    quantity: 9,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
  {
    id: 'jj12',
    name: 'tomato',
    category: 'vegetables',
    img: 'img/tomato.png',
    price: 70,
    quantity: 8,
    url: '#',
    currency: 'UAH',
    description:
      'A goods description is essentially a detailed description that states what the goods are as well as other important information about the goods being shipped.',
  },
];
